### ISSUE TITLE
EnumerableCollection.ToArray() and .ToList() throw

### ISSUE THREAD

**Issue by jeffman** [bobvanderlinden/sharpfilesystem#14]
Because EnumerableCollection.CopyTo() throws NotSupportedException, the standard Linq extensions .ToArray() and .ToList() will also throw because they internally use .CopyTo(). Is there any reason why .CopyTo() isn't supported?

By the way, I was pulling my hair out trying to come up with my own flavour of IFileSystem before I stumbled across this repo -- thanks for saving me lots of work :)

**Comment by bobvanderlinden** [comment]
This should be fixed in 5e6c7ce81f233effd27080fa243b43ad69753e9a. Thanks for reporting the problem.
