### ISSUE TITLE
Question: does SharpZipLibFileSystem support creating huge files?

### ISSUE THREAD

**Issue by vector-man** [bobvanderlinden/sharpfilesystem#9]
I looked over the source code and it appears that SharpZipLibFileSystem stores files in memory when they are created (I'm not positive about that, because I didn't examine everything). Will this prevent files larger than RAM from being created?

**Comment by bobvanderlinden** [comment]
No, it does not. Zip files aren't the greatest for adding/removing files once the zip is already created. It is mostly useful as an readonly filesystem, but it *can* be used as a writable one in-memory. It would be hard to get writable working correctly, as SharpZipLib will start writing the zip file itself once `CommitUpdate` and `Close` is called. At the moment `SharpZipLibFileSystem` will call these upon disposal.

If you want to create large zip files, I'd suggest using `ZipOutputStream` from SharpZipLib itself.

**Comment by vector-man** [comment]
Thanks!
